### PR TITLE
Turbo stream controller typescript compatibility

### LINKED ISSUE #597: [ux-turbo] Multiple typescript errors after upgrade to 6.2
### Symfony version(s) affected

6.2.1

### Description

After upgrading to symfony 6.2.1, webpack cannot compile the assets anymore:
```
 ERROR  Failed to compile with 8 errors                                                                                                                                                                       4:13:47 PM

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(25,19)
      TS2339: Property 'hasHubValue' does not exist on type 'default'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(25,51)
      TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(26,19)
      TS2339: Property 'hasTopicValue' does not exist on type 'default'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(26,53)
      TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(29,32)
      TS2339: Property 'hubValue' does not exist on type 'default'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(30,45)
      TS2339: Property 'topicValue' does not exist on type 'default'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(32,14)
      TS2339: Property 'url' does not exist on type 'default'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(36,40)
      TS2339: Property 'url' does not exist on type 'default'.


```

Using latest versions from all packages, including typescript.
I am not using mercure at all.  

Seems that additional work must be done in the `turbo_stream_controller.ts`, this will pass: 

```
export default class extends Controller {
    static values = {
        topic: String,
        hub: String,
        hasHub: Boolean, // added
        hasTopic: Boolean // added
    };
    es;
    url; // added

    declare readonly topicValue: string; // added
    declare readonly hubValue: string; // added
    declare readonly hasHubValue: boolean; // added
    declare readonly hasTopicValue: boolean; // added

    initialize() {
        const errorMessages: string[] = []; // added type declaration
        if (!this.hasHubValue) errorMessages.push('A "hub" value pointing to the Mercure hub must be provided.');
        if (!this.hasTopicValue) errorMessages.push('A "topic" value must be provided.');
        if (errorMessages.length) throw new Error(errorMessages.join(' '));

        const u = new URL(this.hubValue);
        u.searchParams.append('topic', this.topicValue);

        this.url = u.toString();
    }

    connect() {
        this.es = new EventSource(this.url);
        connectStreamSource(this.es);
    }

    disconnect() {
        this.es.close();
        disconnectStreamSource(this.es);
    }
}
```

I don't know if the above is correct, I just had to do it to be able to compile the assets, but the logic may be faulty.  
Feel free to include it if that's the way to fix the problem.

Best.

### How to reproduce

Use latest version for the above packages.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by twisted1919**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Tickets       | Fix #597
| License       | MIT

### CODE REVIEW

**Comment by weaverryan** [comment]
Finished in #604! I needed this "poke" to figure out what was going wrong and notice that we've been declaring the "value" properties all wrong in other places. We "got away with it" previously. But as soon as you set `allowDeclareFields: true`, all of the "incorrect" properties finally exploded. So, we needed to fix things everywhere - which is a great step forward.

Thanks!
