### ISSUE TITLE
[ux-turbo] Multiple typescript errors after upgrade to 6.2

### ISSUE THREAD

**Issue by twisted1919** [symfony/ux#597]
### Symfony version(s) affected

6.2.1

### Description

After upgrading to symfony 6.2.1, webpack cannot compile the assets anymore:
```
 ERROR  Failed to compile with 8 errors                                                                                                                                                                       4:13:47 PM

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(25,19)
      TS2339: Property 'hasHubValue' does not exist on type 'default'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(25,51)
      TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(26,19)
      TS2339: Property 'hasTopicValue' does not exist on type 'default'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(26,53)
      TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(29,32)
      TS2339: Property 'hubValue' does not exist on type 'default'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(30,45)
      TS2339: Property 'topicValue' does not exist on type 'default'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(32,14)
      TS2339: Property 'url' does not exist on type 'default'.

 error  in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts                                                                                                                             4:13:47 PM

[tsl] ERROR in /srv/app/vendor/symfony/ux-turbo/assets/src/turbo_stream_controller.ts(36,40)
      TS2339: Property 'url' does not exist on type 'default'.


```

Using latest versions from all packages, including typescript.
I am not using mercure at all.  

Seems that additional work must be done in the `turbo_stream_controller.ts`, this will pass: 

```
export default class extends Controller {
    static values = {
        topic: String,
        hub: String,
        hasHub: Boolean, // added
        hasTopic: Boolean // added
    };
    es;
    url; // added

    declare readonly topicValue: string; // added
    declare readonly hubValue: string; // added
    declare readonly hasHubValue: boolean; // added
    declare readonly hasTopicValue: boolean; // added

    initialize() {
        const errorMessages: string[] = []; // added type declaration
        if (!this.hasHubValue) errorMessages.push('A "hub" value pointing to the Mercure hub must be provided.');
        if (!this.hasTopicValue) errorMessages.push('A "topic" value must be provided.');
        if (errorMessages.length) throw new Error(errorMessages.join(' '));

        const u = new URL(this.hubValue);
        u.searchParams.append('topic', this.topicValue);

        this.url = u.toString();
    }

    connect() {
        this.es = new EventSource(this.url);
        connectStreamSource(this.es);
    }

    disconnect() {
        this.es.close();
        disconnectStreamSource(this.es);
    }
}
```

I don't know if the above is correct, I just had to do it to be able to compile the assets, but the logic may be faulty.  
Feel free to include it if that's the way to fix the problem.

Best.

### How to reproduce

Use latest version for the above packages.

**Comment by daFish** [comment]
@twisted1919 Would you mind to open a PR with the fix? We can iterate from there if needed but the fix doesn't look wrong.

**Comment by stof** [comment]
The Symfony UX packages are shipping compiled JS code. So I don't understand why your own project tries to compile the typescript files.

**Comment by twisted1919** [comment]
@stof - That makes two of us. I installed ux-turbo as suggested at https://symfony.com/bundles/ux-turbo/current/index.html#installation and in my package.json I have it listed as:
`"@symfony/ux-turbo": "file:vendor/symfony/ux-turbo/assets",` 
So maybe because it points to the assets folder which contains both the `src` and the `dist` folder and because I am using TS, it chooses to use the `src`? 
But regardless of this, the way that .ts file looks like needs improvements since it's really not passing typescript strict validation, don't you think?

@daFish - Sure, [I worked on this today](https://github.com/twisted1919/symfony-ux/commit/dfbf61ba590bfada3f55308cd16581624ed91172) and I am almost ready for the pull-request, but there's one issue, since we're using `declare` fields, we need to enable this in the babel preset for typescript, so it knows how to handle them: 
`['@babel/preset-typescript', {allowDeclareFields: true}]` but if we do this in the global `babel.config.js` file which applies for all tests, then it will break the tests for whatever reason, so my next approach was to include this change only in the `jest.config.js` for the turbo package, as follows:
```js
// src/Turbo/assets/jest.config.js 
const config = require('../../../jest.config.js');

config.transform = {
    '\\.(j|t)s': ['babel-jest', {
        presets: [
            ['@babel/preset-env', {targets: {node: 'current'}}],
            '@babel/react',
            ['@babel/preset-typescript', {allowDeclareFields: true}],
        ],
    }]
};

module.exports = config;
```
Please note that `allowDeclareFields` will be true by default starting with babel 8, see https://babeljs.io/docs/en/babel-preset-typescript#allowdeclarefields  
So while the above seem to work, maybe we should find a fix that can work for all tests, as this really looks a bit like a hack.

**Comment by daFish** [comment]
@twisted1919 Another idea I had was to use `.gitattributes` to prevent the export of the source files when installing the component(s). Just like the other Symfony components do it.
But this should be in addition to your fix.

**Comment by weaverryan** [comment]
> @twisted1919 Another idea I had was to use .gitattributes to prevent the export of the source files when installing the component(s).

That makes sense to me. I don't think that npm packages typically ship their source `.ts` files. And so we shouldn't either.

@twisted1919 With your patch, I'm not having any problems locally with the build. Or, to say it better, those fixes fix those particular TypeScript problems - the build has no problems with the missing `allowDeclareFields`. Are you sure that's needed? We already have a few `declare` in the codebase.

Also, we should definitely fix the TS errors in LiveComponents (they're left over from the fact that many of the components started as `.js` files and were converted to `.ts`). However, we should also make sure your app isn't processing those .ts files :). Recently, another user had this problem. The fix was to add this to the ts config:

```
"exclude": [
        "vendor/symfony/**/assets/src",
        "vendor/symfony/**/assets/test"
    ]
```

**Comment by twisted1919** [comment]
@weaverryan - Thank you for the provided fix, that indeed solves the problem.
I also opened a pull request, take a look, up to you to merge it or not, I did my best given circumstances. 
As for failed tests, iI just cloned the repo, created the branch, applied the changes and ran the tests and they failed as I mentioned above.

**Comment by daFish** [comment]
@weaverryan PR regarding the `.gitattributes`-changes has been opened with #601
