### ISSUE TITLE
[LiveComponent] Running `npm install --force` fails with "This is related to npm not being able to find a file."

### ISSUE THREAD

**Issue by brabli** [symfony/ux#1567]
When trying to install the latest version of UX Live Component I can successfully install the package with composer.
When I run `npm install --force` however the command fails with an error message that suggests it can't find a file (see image).

<img width="428" alt="npm_output" src="https://github.com/symfony/ux/assets/67018167/366d1ffd-8fa5-45c0-9667-d77c8db01f7f">

My `package.json` points at a file in my vendor folder:
```json
"@symfony/ux-live-component": "file:vendor/symfony/ux-live-component/assets",
```
...and upon inspection the directory in question it appears to look fine, containing it's own `package.json` alongside a `dist` and `styles` directory.

I have attatched the npm log file in case it's useful at all.

[2024-03-01T13_00_54_787Z-debug-0.log](https://github.com/symfony/ux/files/14461498/2024-03-01T13_00_54_787Z-debug-0.log)

**Comment by pcmmf** [comment]
Just to confirm I have the same issue. It occurred after a `composer update` to the v2.16.0 versions of the bundles.

**Comment by smnandre** [comment]
Could it be related to this dependency ?

```
"dependencies": {
        "idiomorph": "https://github.com/bigskysoftware/idiomorph.git"
 },
```

**Comment by pcmmf** [comment]
Yes, removing that from `vendor/symfony/ux-live-component/assets/package.json` did allow `npm` to run, but anything that used the live components obviously wouldn't work properly.

**Comment by smnandre** [comment]
If you try with this, does it work better ? 

```
"dependencies": {
        "idiomorph": "github:bigskysoftware/idiomorph"
 },
 ```

**Comment by pcmmf** [comment]
It doesn't seem to help in my case. I patched the file manually, but still receive the following:

```bash
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

With the line removed altogether, `npm update` works fine.

**Comment by smnandre** [comment]
Last attempt (but maybe the good one 🤞 )

```
"dependencies": {
        "idiomorph": "^0.3.0"
 },
```

**Comment by pcmmf** [comment]
With that change, `npm update` now works, but it seems the live components are not working. I have a form based live component which worked prior to this issue. Now, the page is POSTed - seemingly the JavaScript isn't intercepting the request.  I get a console error of:
```
405.4e849f84.js:2 Error invoking action "submit->live#action" Error: No action name provided on element. Did you forget to add the "data-live-action-param" attribute?
```

Prior to 2.16, my component twig looked like this:
```html
{{ form_start(form, {
        attr: {
            'novalidate': true,
            'data-action': 'live#action',
            'data-action-name': 'prevent|calculate',
        }
    }) }}
```

I tried changing this to:

```html
{{ form_start(form, {
        attr: {
            'novalidate': true,
            'data-action': 'live#action',
            'data-live-action-param': 'prevent|calculate',
        }
    }) }}
```

This then gives the console error: `app.728fce7b.js:1 Unknown modifier prevent in action "prevent|calculate". Available modifiers are: stop, self, debounce, files.`

So, it seems the change to the dependencies you mentioned @smnandre works, but I potentially have some other tidying up to do to make it work with v2.16.

**Comment by smnandre** [comment]
Indeed you'll have a bit of work, but this should go well (i hope) : https://github.com/symfony/ux/blob/2.x/UPGRADE.md

**Comment by smnandre** [comment]
Thank you for testing this, i'll open a PR to fix the bug.

**Comment by pcmmf** [comment]
@smnandre No problem. The changes from the UPGRADE.md work fine too, thanks!
