### ISSUE TITLE
After update chart is not loading anymore

### ISSUE THREAD

**Issue by shyim** [symfony/ux#21]
After updating to the ux-chartjs to 1.1.0 it does not work anymore 🙈 

JS Error
```
definition.js:20 Uncaught (in promise) TypeError: constructor.bless is not a function
    at blessControllerConstructor (definition.js:20)
    at blessDefinition (definition.js:15)
    at new Module (module.js:6)
    at Router.push../node_modules/@stimulus/core/dist/src/router.js.Router.loadDefinition (router.js:54)
    at application.js:81
    at Array.forEach (<anonymous>)
    at Application.push../node_modules/@stimulus/core/dist/src/application.js.Application.load (application.js:81)
    at Application.push../node_modules/@stimulus/core/dist/src/application.js.Application.register (application.js:72)
    at index.js:35
````

What did I run
* composer update
* composer recipes:install symfony/web-profiler-bundle --force
* npm update --force
* npm run dev

Also npm update without force has very weird error message

```
❯ npm update
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: stimulus@1.1.1
npm ERR! node_modules/stimulus
npm ERR!   dev stimulus@"^1.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer stimulus@"^2.0" from @symfony/stimulus-bridge@1.1.0
npm ERR! node_modules/@symfony/stimulus-bridge
npm ERR!   dev @symfony/stimulus-bridge@"^1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/shyim/.npm/eresolve-report.txt for a full report.
```

I have locked now `@symfony/stimulus-bridge` in npm and `symfony/ux-chartjs` in composer to 1.0,0 and it works again for me 😅

**Comment by tgalopin** [comment]
Hi! You probably need to update Stimulus to 2.0 in your package.json file if you didn't already. That may be the source of the issue.

To update, simply change the reference to Stimulus 2 in your package.json file or apply the new Webpack Encore recipe.

**Comment by shyim** [comment]
Ahh 🙈 
Didn't see that. I guessed that is a dependency of `@symfony/stimulus-bridge` and not in my package.json 😅

**Comment by tgalopin** [comment]
It's not your fault: usually, we shouldn't do this (and we won't ever again), as upgrading an indirect dependency is a BC break. However, in this specific situation, because both Stimulus 2 and Symfony UX were released so close together, we estimated people didn't spend too much time on either to actually have big issues on large project to upgrade.

In the future, this need to manually change your package.json won't happen again until you actually wish to upgrade from one major to another, just like any Symfony PHP component BC policy :) .
